domain:
    resource: '../src/Domain/Controller'
    type: attribute

computer:
    resource: '../src/Computer/Controller'
    type: attribute

multiplayer:
    resource: '../src/Multiplayer/Controller'
    type: attribute

security:
    resource: '../src/Security/Controller'
    type: attribute

shared:
    resource: '../src/Shared/Controller'
    type: attribute

admin:
    resource: '../src/Admin/Controller'
    type: attribute
