# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    mailer_from_address: '%env(MAILER_FROM_ADDRESS)%'
    app_domain: '%env(APP_DOMAIN)%'
    elastic_host: '%env(ELASTIC_HOST)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Domain\:
        resource: '../src/Domain/*'
        exclude:
            - '../src/Domain/Entity/'

    Computer\:
        resource: '../src/Computer/*'
        exclude:
            - '../src/Computer/Entity/'

    Multiplayer\:
        resource: '../src/Multiplayer/*'
        exclude:
             - '../src/Multiplayer/Entity/'

    Security\:
        resource: '../src/Security/*'
        exclude:
            - '../src/Security/Entity'

    Admin\:
        resource: '../src/Admin/*'

    DataFixtures\:
        resource: '../src/DataFixtures/*'

    Mailer\:
        resource: '../src/Mailer/*'

    Elastic\:
        resource: '../src/Elastic/*'

    Domain\Controller\:
        resource: '../src/Domain/Controller/'
        tags: ['controller.service_arguments']

    Computer\Controller\:
        resource: '../src/Computer/Controller/'
        tags: ['controller.service_arguments']

    Multiplayer\Controller\:
        resource: '../src/Multiplayer/Controller/'
        tags: ['controller.service_arguments']

    Security\Controller\:
        resource: '../src/Security/Controller/'
        tags: ['controller.service_arguments']

    Admin\Controller\:
        resource: '../src/Admin/Controller/'
        tags: [ 'controller.service_arguments' ]

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
