services:
    _defaults:
        autowire: true
        autoconfigure: true

    Tests\Common\Fixtures:
        public: true

    Multiplayer\Service\SecretGenerator:
        public: true

    Multiplayer\MultiplayerFacade:
        public: true
